### PR TITLE
Colored output

### PR DESCRIPTION
**Pull request by Apanatshka**
I just started with implementing #7. 
Right now it only does automatic detection and colouring, and I made the header row bold to make it more distinctive. 

Still needs the flag, so don't merge yet.

### CODE REVIEW

**Comment by Apanatshka** [comment]
Ok, the color flag was also simple to add. 

@BurntSushi: ready for review.

**Comment by Apanatshka** [comment]
@BurntSushi: Do you have time to review this? It's a small diff..

**Comment by Apanatshka** [comment]
@BurntSushi: Since I have your attention, can you review this PR too? It's a tiny change :)

**Comment by BurntSushi** [comment]
Let's do it. Thanks!

**Pull request merged**
